bottlesdevs/Bottles

bottles/window.py

By the way, I think that your /usr(/local)/bin/bottles directory should be /usr(/local)/share/bottles instead.

Search for style.css in `/usr/bin/` too

---

README.md

- fixed build commands ( cd into build folder )
- compile with parallel processes ( ninja -j$(nproc) )

Update README.md - Build section

---

README.md

Fixed Repository Link
- Added new link

Updated REPO Link

---

bottles/locale/de_DE/LC_MESSAGES/bottles.po

Hi, I was just checking out Bottles in elementaryOS Hera (which has 0.2.5 packaged) and noticed that some German translations are off. 
I could also add German translation on master branch for v2 if desired. 
Fixes : did not create issue for it
locale strings update not tested - if needed I could try to build & test

update de (german) localization

---

po/fr.po

All strings in English were translated in French to the best of my ability, any suggestion on the current translation to make it better is welcomed !
I didn't test the changes (since I just discovered this tool a day ago, but I will definitely try it out soon enough and report here any test/bug I saw if there are any), but I suppose that such a change (support a new language) will not break the execution of the program.

Full Translation in french

---

src/download.py
src/pages/add.py
src/pages/create.py
src/pages/details.py
src/pages/list.py
src/pages/preferences.py
src/runner.py
src/ui/add-details.ui
src/ui/bottles.gresource.xml
src/ui/create.ui
src/ui/details.ui
src/ui/dxvk-entry.ui
src/ui/list-entry.ui
src/ui/runner-entry.ui
src/ui/state-entry.ui
src/ui/style.css
src/utils.py
src/window.py

This update introduces the _experimental bottle versioning feature_.
It is precisely an experimental, unstable, potentially harmful feature in its current state!
I take this opportunity to wish you all **a wonderful 2021**, hoping this will be an ambitious year as much as this feature!
The versioning system is only available for bottles with a custom environment (at the moment).
A new purple tag is shown in the bottle list indicating which state is active.
The new Versioning tab is only shown if this is active. From here you can check the created states, create new ones and restore to a specific state.
This is a similar concept to git. When the bottle is created, State 0 is generated, containing all the files of the bottle and traces them to a json file with the relative checksums. At any …

Bottles versioning (🎉 Happy 2021 🥳)

---

README.md

Packaged and available in official Fedora repos. Awesome app!
It's now on QA:
- f32 https://bodhi.fedoraproject.org/updates/FEDORA-2021-0c8295842d
- f33 https://bodhi.fedoraproject.org/updates/FEDORA-2021-2c83cc1e58

docs: Update Fedora installation instructions

---

data/com.usebottles.bottles.appdata.xml.in

More in line with the changes made to other stings.
What is "<content_attribute id="sex-homosexuality">none</content_attribute>" good for?
There are already a bunch of other categories to cover it…?
Fixes #(issue)

Appdata strings reworked

---

src/ui/window.ui

Uses the right icon for the back button.

window: use a symbolic back icon

---

.deepsource.toml
src/pages/list.py
src/pages/new.py
src/pages/onboard.py
src/pages/preferences.py
src/runner.py
src/utils.py
src/window.py

I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/Bottles/) that can improve the general code quality here.
This PR fixes a few of the issues detected.
- Remove mixed tabs and spaces from some indents.
- Merge unnecessary nested `if`s.
- Fix dangerous default argument (mutable used as default arg).
- Refactor `if` expression to simplify.
- Remove unused imports.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

Refactor code quality issues

---

AppImageBuilder.yml

should fix  (SSL_certificate)

---

src/ui/dialog-dll-overrides.ui
src/ui/dialog-environment-variables.ui
src/ui/dialog-launch-options.ui
src/ui/new.ui
src/ui/onboard.ui

It keeps HdyWindow and HdyApplicationwindow draggable.

Use HdyHeaderBar

---

src/pages/onboard.py
src/ui/onboard.ui

This refactors how page changes are affecting buttons, making it much more robust and consistent, and this refines the button styles and sizing a bit.

Fix the onboard buttons

---

src/ui/breeze.css
src/ui/dependency-entry.ui
src/ui/details.ui
src/ui/dialog-dll-overrides.ui
src/ui/dll-override-entry.ui
src/ui/download-entry.ui
src/ui/dxvk-entry.ui
src/ui/importer-entry.ui
src/ui/installer-entry.ui
src/ui/list-entry.ui
src/ui/new.ui
src/ui/program-entry.ui
src/ui/runner-entry.ui
src/ui/state-entry.ui
src/ui/style.css

Let's use the standard style classes here. This also fixes the outline's
radius.

style: Replace .btn_radius by .circular and .image-button

---

com.usebottles.bottles.json

```
cd Bottles
flatpak-builder --user --force-clean --install-deps-from=flathub flatpak com.usebottles.bottles.json
```
Before this PR: `Error: module bottles: Can’t recursively copy directory`
After this PR:     :partying_face: 
flatpak-builder 1.0.12

Fix flatpak manifest for building

---

.github/workflows/build_pkgs_unstable.yml
.gitignore

Fixes #434 
I tested by temporary adding 
```
on:
push:
branches: [ master ]
```
to the workflow, I have now removed it.
Here are the logs proving the build was successful:
[10_Build flatpak.txt](https://github.com/bottlesdevs/Bottles/files/6948990/10_Build.flatpak.txt)

Add flatpak to build_pkgs_unstable workflow

---

.github/workflows/build_pkgs_unstable.yml

The relase system was saturated by the unstable builds, now they will be added down in the actions menu
Fixes #(issue)
NOTE: The artifacts are zipped and we cannot solve it...

Fix unstable relase system

---

data/com.usebottles.bottles.appdata.xml.in

Fix broken display_length size constant mentioned in https://github.com/bottlesdevs/Bottles/pull/523#discussion_r703726912

Fix display_length requirement in appdata

---

src/main.py
src/window.py

An attempt to add the functionality of passing arguments to an application inside a bottle from the command line, fixing #686.
I have not thoroughly tested this as I am unfamiliar with the code base.

Allow passing arguments to an application

---

src/backend/globals.py
src/backend/notifications.py

merge double ifs

---

data/com.usebottles.bottles.appdata.xml.in

make developer_name tag untranslatable

---

src/backend/globals.py
src/utils.py
src/window.py

We should have less flatpak-specific quirks.
Fixes #997

Follow XDG_DATA_HOME rather than having flatpak tweaks

---

com.usebottles.bottles.dev.yml

chore: standard permissions - Enable OpenGL rendering

---

src/views/bottle_preferences.py

Fixed race condition when switching DXVK,VKD3D,NVAPI libraries version.
Race condition leads to inconsistent state of library installation, when different dlls can belong to
different versions of library.
and in library source directory

Fixed race condition when switching DXVK,VKD3D,NVAPI libraries version

---

src/backend/utils/terminal.py

Added kitty as a terminal.
Launches kitty when it is installed.

Add kitty as a terminal option

---

src/ui/about.ui

This Pull Request fixes a wrong translation credit attribution in the `src/ui/about.ui` file.

Fix translation credit attribution in `about.ui`

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/feedback.md

This MR improves some areas in issue forms:
- Adds capitalization in the names for consistency
- Improves clarification
- Adds a new section for which display backend Bottles is running on
Fixes #1202
- Can be seen in https://github.com/TheEvilSkeleton/Bottles/issues/new/choose.

Improve issue forms

---

.github/workflows/continuous-deb-build.yml

This fixes ci not working on branch `v1`. If you want I can change the ${{ github.sha }} variable as it is quite long.
Fixes #(issue)
Fixes Ci on `v1` branch not working
I tested this by creating a test branch of `patch-1` which automatically created release.

ci(v1 branch): fix ci builds

---

src/backend/managers/runtime.py
src/backend/managers/steam.py

Add some small improvements

---

src/ui/preferences.ui

Typo in the UI
Incorrect spelling `Apperance`
Correct spelling `Appearance`
Fixes #(issue)
Translation files will probably need to be updated. I am not sure if that will break things.
I have not tested it

fix typo - Appearance

---

CODE_OF_CONDUCT.md
README.md

Formally adopt GNOME CoC

---

data/com.usebottles.bottles.appdata.xml.in

This PR simply adds the 2 new URL types vcs-browser and contribute to the Appdata file.

Add new URL types to Appdata

---

src/window.py

Fixes #(issue)
(Translation)
Untested.

Fix typo in custom bottles path

---

src/backend/utils/terminal.py

Add Gnomes new default terminal kgx

---

src/utils/gtk.py
src/views/new.py

Fixes #1709 
- Follow procedure to reproduce original issue, issue doesn't appear

fix issue of being able to add colon to bottle name

---

po/LINGUAS

Reverts bottlesdevs/Bottles#1693

Revert "i18n: Fix Chinese translation not available (#1692)"

---

src/backend/managers/conf.py

This change allows ConfigManager to also parse configs that are stored as strings, instead of only being able to read and parse
files.
- Use python from the terminal to import and test out parsing a config string
- Use Bottles to create a new bottle and install dependencies as well as applications

Allow ConfigManager to take configuration strings

---

src/dialogs/gamescope.py
src/ui/dialog-gamescope.ui

- Allows to press Esc to close the window
- Uses window.close action instead of signals
- Add mnemonic for `C`
Related to: https://github.com/bottlesdevs/Bottles/issues/1598.

More Gamescope improvements

---

src/dialogs/launchoptions.py
src/ui/dialog-launch-options.ui

- Use `activatable-widget` when available
- Port to AdwHeaderBar
- Rewrite save functions
- Reimplement close action
- Use mnemonic for Cancel
Related to https://github.com/bottlesdevs/Bottles/issues/1598.

Improve Launch Options dialog

---

src/dialogs/launchoptions.py

Remove redundant cancel button

Remove redundant cancel button

---

src/ui/program-entry.ui

Add separator for program-entry

---

src/backend/models/bottle.py
src/backend/models/samples.py
src/backend/wine/winecommand.py
src/ui/details-preferences.ui
src/views/bottle_preferences.py

Needed to implement https://github.com/bottlesdevs/Bottles/issues/1837, as agreed on Discord.

Remove DXVK Hud

---

src/backend/managers/repository.py

Imports the `http` library in src/backend/managers/repository.py
Fixes #1856 
- Launch bottles without internet access

add http import

---

.github/ISSUE_TEMPLATE/bug.yml

Update issue template to reflect the latest version of Bottles.

Update issue template

---

src/views/library.py

makes sure it actually removes the space between program names for classes (let's hope the last fix for this)

Yet another library menu button fix

---

src/backend/wine/winecommand.py

Closes https://github.com/bottlesdevs/Bottles/issues/1838.

Make Gamescope compatible with FSR

---

src/views/preferences.py

Bind the active state of switches to the corresponding settings, cutting down on code

Simplify preferences implementation

---

src/window.py

Adds vmtouch to the credits in the about window
- Open about window
- check if vmtouch entry is present
- check if vmtouch entry takes you to the vmtouch github page

add vmtouch to credits

---

bottles/frontend/ui/dialog-drives.ui
bottles/frontend/ui/dialog-env-vars.ui
bottles/frontend/ui/dialog-exclusion-patterns.ui
bottles/frontend/ui/dialog-gamescope.ui
bottles/frontend/ui/dialog-vmtouch.ui

Insert `GtkShortcutController` directly under dialog to make Escape
functional anywhere in the screen

Close window when pressing Escape from anywhee

---

com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml

This bumps libadwaita in Flatpak manifests.

Bump libadwaita

---

po/ta.po

**I am adding information about copyright and the first author to ta.po (Tamil translation file).** 
I have been using bottles for some time. It has been a fantastic and smooth experience running applications and games under bottles. I Thank you guys for creating and maintaining this project. Translating Bottles to Tamil is just a small contribution from me to this project. Planning to contribute more in the future. 
Regards,
Dharun

Update ta.po: add copyright, first author

---

bottles/frontend/ui/about.ui
bottles/frontend/ui/details-bottle.ui
bottles/frontend/ui/details-preferences.ui
bottles/frontend/ui/importer-entry.ui
bottles/frontend/ui/importer.ui

I fixed some typos, and improved where I thought it could be.
Fixes #(issue)
Doesn't fix an issue, but improves the user experience.
- I have not tested my changes yet.

Makes some small improvements to the UI

---

bottles/frontend/ui/dialog-crash-report.ui
bottles/frontend/windows/crash.py

Improve crash report. Related to https://github.com/bottlesdevs/Bottles/issues/1598.

Improve crash report

---

bottles/frontend/ui/about.ui

Adding my name in translator credits.

about.ui: add @kbdharun to translator-credits

---

com.usebottles.bottles.dev.json

Update the json flatpak manifest to match the  yml one.
Fixes #(issue)

Update json flatpak manifest

---

com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml

Update libadwaita from beta to rc in the manifest.
Fixes #(issue)

Update libadwaita to rc

---

bottles/frontend/ui/details-preferences.ui
bottles/frontend/views/bottle_preferences.py

This MR only adds options that are only related to your setup. For example, if you are using an NVIDIA GPU, then DXVK-NVAPI will appear on Bottles. If you are not using Flatpak, then Bottles Runtime appear.
Closes https://github.com/bottlesdevs/Bottles/issues/2032.

Set redundant rows to "disabled"

---

bottles/backend/globals.py
bottles/backend/logger.py
bottles/backend/managers/data.py
bottles/backend/managers/journal.py
bottles/backend/managers/steam.py
bottles/backend/utils/file.py
bottles/backend/utils/manager.py
bottles/frontend/widgets/program.py
bottles/frontend/windows/main_window.py
com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml

I have yet to test all of these changes.
Some commits as [Use GLib.compute_checksum instead of hashlib](https://github.com/bottlesdevs/Bottles/commit/aa5418b3f11aaedf742e93086797b8ba78837515), [file: Use g_format_size to get human readable size](https://github.com/bottlesdevs/Bottles/commit/82a2a86954a09315843a8421f4b28c8967691f5f) are not really needed but can make maintenance simpler.

Some random improvements

---

bottles/frontend/windows/main_window.py

Improve About page by adding more links and information.
- Move third parties to Acknowledgement section
- Add sponsors to Acknowledgement section
- Add donation (funding) link

frontend: Improve About page

---

README.md
bottles/frontend/ui/about.blp
data/com.usebottles.bottles.appdata.xml.in
data/com.usebottles.bottles.desktop.in

This PR improves the Bottles desktop file comment to make more sense.

Improve Bottles desktop entry comment

---

bottles/backend/dlls/nvapi.py

A typo caused the old fix to not work. Sorry for the inconvinience.
Fixes #(issue)

nvapi hotfix

---

bottles/frontend/widgets/installer.py

This adds tooltips to each entry in the installer, to better indicate the stability of each program.
Thoughts?
Related to https://github.com/bottlesdevs/Bottles/issues/2126.

frontend: Add grade tooltips

---

bottles/frontend/ui/dialog-vkbasalt.blp
bottles/frontend/ui/preferences.blp

This adds `activatable-widget` for Bottles Directory.

frontend: Minor consistency fixes

---

.github/ISSUE_TEMPLATE/bug.yml

This updates the issue template to something more legible and, in my opinion, less distracting. I removed mentions of unofficial packages since many issues we get have already gotten fixed. It's best to encourage users to use whatever we officially support.
Preview: https://github.com/bottlesdevs/Bottles/blob/update-issue-template/.github/ISSUE_TEMPLATE/bug.yml

misc: Update issue form

---

bottles/backend/utils/terminal.py
bottles/backend/wine/winecommand.py

Fixes #2273
Tested with the protocol in #2273

Fix missing cwd variable when launching a program with terminal

---

bottles/frontend/ui/library-entry.blp
bottles/frontend/ui/library.blp
bottles/frontend/ui/style.css
bottles/frontend/views/library.py
bottles/frontend/widgets/library.py
bottles/frontend/widgets/program.py
bottles/frontend/windows/main_window.py
com.usebottles.bottles.dev.yml

https://user-images.githubusercontent.com/9479903/202860074-cde369c0-86b2-430b-be61-80c50e741028.mp4

Revamp Library page

---

bottles/frontend/views/bottle_preferences.py

This adds tooltips for unavailable extensions.
Closes https://github.com/bottlesdevs/Bottles/issues/2360.

frontend: Add tooltips for extensions

---

bottles/frontend/windows/gamescope.py

- Use `.get()` to get value from config
- Use consistent syntax for getting value
This fixes the bug found in https://github.com/bottlesdevs/Bottles/pull/2373#issuecomment-1355594029.

frontend: Gamescope improvements

---

bottles/backend/managers/dependency.py

Try to fix https://github.com/bottlesdevs/Bottles/issues/2375
not tested because I use immutable OS

fix: dependency replace_font step

---

.github/ISSUE_TEMPLATE/bug.yml
bottles/backend/health.py

- Remove distro entry, since Flatpak shows GNOME
- Add DE/WM entry
- Remove unnecessary entries in issue form

backend: Improve health check

---

bottles/frontend/utils/connection.py

Updated the link to check if the user has an internet connection (both IPv4 and IPv6)
Changed the link to check if the user is connected to the internet

Frontend: Updated link for connection checking

---

bottles/backend/managers/manager.py

there is a typo in create_bottle_from_config()

fix: create_bottle_from_config() nvapi check

---

bottles/backend/managers/component.py

Fixes #2420, #2424
Not tested, but followed what was done in other places in the code

fix: wrong exception catching using pycurl

---

bottles/backend/managers/component.py
bottles/backend/utils/decorators.py

Replace spin-lock with threading.Lock, improving responsiveness for component install operation

fix: replace spin-lock with threading.Lock

---

bottles/backend/managers/repository.py

Fixes not being able to use local repositories. When using pycurl with files will always return 0 for the response code and thats makes dont work.
Also i make in a way that i guess is better for like future custom repositories that you can add.

fix: being able to use local repos with pycurl

---

bottles/backend/managers/manager.py

make confused log clear.
separated PR requested by @jannuary

misc: improve check_runners() log

---

bottles/frontend/ui/details-installers.blp

This removes a misleading statement in the installers UI.
Closes #2460

frontend: Improve sentence in installers

---

CONTRIBUTING.md

This updates the contributing information to reflect more up to date information.
- See branch

misc: Update contributing information

---

bottles/backend/models/bottle.py
bottles/backend/wine/executor.py
bottles/frontend/views/bottle_preferences.py

This fixes more issues related to FSR.
Fixes https://github.com/bottlesdevs/Bottles/issues/2482

fsr: Fix more FSR related issues

---

bottles/backend/wine/reg.py
bottles/frontend/widgets/dependency.py

Fix "dependency installed" toast while uninstalling dependency.
Fix `Reg.bulk_add()` log message typo

fix: hint texts

---

bottles/frontend/views/bottle_preferences.py

This is quite a big oversight
Fixes probably stuff

fix: wrong combo selected for VKD3D

---

.github/workflows/pylint-checker.yml
.github/workflows/pylint-commenter.yml
.pylintrc

This adds a Github Action that will run on each PR, checking the files modified by the PR for linting, to show different errors.

code: Add Pylint GitHub Actions against PRs

---

bottles/backend/downloader.py

fix: downloads not working if no terminal

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Closes https://github.com/bottlesdevs/Bottles/issues/2532
- See https://github.com/bottlesdevs/Bottles/blob/update-issue-form/.github/ISSUE_TEMPLATE/bug.yml

misc: Update issue forms

---

bottles/frontend/views/importer.py

:/
Fixes https://github.com/bottlesdevs/Bottles/issues/2623

fix: Invert `get_file()` and `get_path()`

---

bottles/frontend/views/bottle_details.py

This adds a toast whenever the user runs an executable from the "Run Executable" button.
Closes https://github.com/bottlesdevs/Bottles/issues/2604

frontend: Add toast for "Run Executable"

---

com.usebottles.bottles.yml

Just ugh. The only reason we even have it is because of an earlier overengineered implementation of a stupid little button in the library view, which has since been changed, but the dead code still remained until recently. 

flatpak: Remove Pillow

---

bottles/backend/managers/manager.py

Make sure ListView gets updated properly when deleting a bottle

---

bottles/frontend/windows/launchoptions.py

Fixes https://github.com/bottlesdevs/Bottles/issues/2693
This also rewords the dialog.

fix: Properly set paths for launch options dialog

---

bottles/backend/managers/manager.py
bottles/backend/repos/repo.py
bottles/backend/state.py
bottles/frontend/views/bottle_dependencies.py
bottles/frontend/views/preferences.py
bottles/tests/state/test_events.py

This adds the EventManager class + some events, and tests about it.
Based on the work here: https://github.com/bottlesdevs/Bottles/pull/2597
Fixes #(issue)

Added event manager + tests

---

bottles/backend/wine/reg.py

Fix crash when creating a bottle

---

bottles/backend/managers/dependency.py

Fix patool double extraction again

---

bottles/backend/managers/backup.py
bottles/backend/managers/component.py
bottles/backend/managers/dependency.py
bottles/backend/managers/manager.py
bottles/backend/managers/repository.py
bottles/backend/managers/steam.py
bottles/backend/managers/versioning.py
bottles/backend/state.py
bottles/backend/utils/connection.py
bottles/backend/utils/manager.py
bottles/frontend/operation.py
bottles/frontend/views/list.py
bottles/frontend/windows/display.py
bottles/frontend/windows/main_window.py

Splitting `class State` as we discussed before @Kinsteen

[backend-rewrite] splitting State class

---

com.usebottles.bottles.yml

flatpak: Update runtime

---

.github/workflows/pytest.yml

As we now have a start of a test framework, we can have pytest run automatically on each push on main, and on each PR. We should also require tests on PRs that need them, before merging them.

[code]: Add pytest action

---

.github/workflows/mypy.yml

Test SonarQube

---

README.md

We switched to Discord a while ago, so I'm getting rid of Telegram in favor of Discord.

readme: Replace Telegram with Discord

---

bottles/frontend/ui/new.blp

It's self-explanatory that the "Name" will be the name of the bottle.

frontend: Rename "Bottle Name" to "Name"

---

bottles/backend/wine/executor.py
bottles/backend/wine/winecommand.py
com.usebottles.bottles.yml

fix: LatencyFlex

---

bottles/backend/managers/manager.py
bottles/backend/models/samples.py
bottles/backend/utils/vulkan.py
bottles/frontend/windows/envvars.py
sonar-project.properties

Because a picture is worth a thousand words, before:
After:
Also include a minor fix: use the correct fsync sync method for gaming environment.
And a minor feature: allow the environment variable value to be set directly by using `variable=value` in the text field.
Fixes #3060
Locally built flatpak.

fix: Wrong programs name and empty program entries

---

bottles/backend/managers/dependency.py
bottles/backend/managers/manager.py
bottles/backend/repos/repo.py
bottles/backend/wine/winecommand.py

Fixes #3061
Fixes #2940
Tested locally.

fix: Do not show success with failed dependencies install

---

bottles/backend/managers/manager.py
bottles/backend/utils/file.py

performance: Use case-fold for drive_c when available

---

README.md

Added HyperBit SRLs as a Sponsor

Added HyperBit SRLs as a sponsor

---

bottles/frontend/main.py
bottles/frontend/meson.build
bottles/frontend/windows/main_window.py

For context: https://usebottles.com/posts/2022-06-07-an-open-letter/ and https://github.com/bottlesdevs/Bottles/issues/2345
It's been 2 years, yet we've seen several cases of distributions fucking up Bottles one way or another, so it's best to protect future users by exiting on non-sandboxed environments.

main: Exit on non-sandboxed environments

---

bottles/frontend/cli/cli.py

Restore line accidentally deleted in 5439cf0
Fixes #3595

Restore line accidentally deleted in 5439cf0

---

bottles/frontend/ui/details-preferences.blp
bottles/frontend/views/bottle_preferences.py
bottles/frontend/windows/fsr.py
bottles/frontend/windows/mangohud.py
bottles/frontend/windows/vkbasalt.py

Reverts bottlesdevs/Bottles#3591

Revert "Make bottle preferences code hotter"

---

.github/workflows/update-manifest.yml
CODING_GUIDE.md

If everything works well, https://github.com/bottlesdevs/Bottles/pull/3753 should update itself to reflect the new changes.

chore: Update dependency list updater

---

bottles/backend/managers/data.py
bottles/backend/managers/journal.py
bottles/backend/models/samples.py
bottles/frontend/window.py

This PR adds an AdwMessageDialog prompting for donations. It reads the oldest entry from the Journal Manager and shows the dialog if it’s older than 7 days. Users can choose to hide this message permanently, that preference is stored in data.yml.

Donation dialog
