data/meson.build

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
By appstream-glib tool https://github.com/hughsie/appstream-glib. It's available on Flathub and Linux distros.

fix: The AppData files now go to /usr/share/metainfo

---

po/bottles.pot
po/da.po
po/de.po
po/es.po
po/fr.po
po/hr.po
po/id.po
po/it.po
po/ja.po
po/la.po
po/nb_NO.po
po/nl.po
po/pl.po
po/pt.po
po/pt_BR.po
po/ru.po
po/sk.po
po/sl.po
po/sv.po
po/tr.po
src/ui/details.ui

Fixed a typo in the UI strings (PluseAudio -> PulseAudio). Probably will need replacing that string in Weblate before the next automatic translation PR comes in.
Fixes #(issue)
Typo in the Preferences menu

Fixed a typo in UI (PluseAudio)

---

src/ui/dependency-entry.ui
src/ui/details.ui

This makes no denpendency row selectable as they have no reason to be.

Polish the dependencies list a bit

---

data/com.usebottles.bottles.desktop.in

Helps with #413 
1. This helps the desktop understand how file opening works with the app. See https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables
2. In addition, and more importantly, this let flatpak users open any file with Bottles, no matter where they are and without fs permissions. Without this Right Click -> Open with Bottles cannot work .
```sh
flatpak-builder --user --force-clean --install-deps-from=flathub --install flatpak com.usebottles.bottles.json
cat ~/.local/share/flatpak/exports/share/applications/com.usebottles.bottles.desktop
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bottles com.usebottles.bottles
Exec=/usr/bin/flatpak run --branch=master --arch=x86_64 --command=bottles --file-forwarding …
```

Add file opening to desktop file

---

src/main.py

Hello everyone. The code change is tiny but it took me some hours on `pdb` and search engines to find the solution.
Reference documentation:
- https://pygobject.readthedocs.io/en/latest/guide/api/signals.html - with the signals currently available for the Python library. This includes `command-line` and `handle-local-options`.
- https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/tests/test_gio.py - to check some examples of `do_command_line`. I couldn't find the error string in the source code, though.
- https://docs.python.org/3/library/pdb.html#debugger-commands - the `pdb` manual because it helped.
- https://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html#example - more `do_command_line` examples.
- https://wiki.gnome.org/HowDoI/GtkApplication - `GtkApplication` …

Add a return value to do_command_line function

---

AppImageBuilder.yml

Fix the AppImage being unable to run on Ubuntu 20.04 LTS by including the missing libraries libffi8 and libhandy in the AppImage Builder, since the AppImage should be portable enough to still run on Ubuntu 20.04 LTS. 
Fixes #(issue)
#756 

Added libffi8ubuntu1 and libhandy-1-0 with libraries included

---

src/backend/runner.py

After a292d5a692bf69623e47150b086c9df2bf264e07, getting the first gpu vendor was failing with the following stack trace:
```
(19:44:55) INFO Using Xwayland.. 
(19:44:55) ERROR Error while running async job: <function Runner.run_command at 0x7fbf787a4280>
Exception: 'dict_keys' object is not subscriptable 
File "/app/share/bottles/bottles/utils.py", line 337, in __target
result = self.task_func(*args, **kwargs)
File "/app/share/bottles/bottles/backend/runner.py", line 488, in run_command
_first = gpu["vendors"].keys()[0]
```
- After the change, the error does not occur anymore and applications start as expected.

Fix getting the first Vulkan ICD gpu vendor 

---

src/backend/runner.py

Fixes a typo in one of the registry keys provided in `runner.py` 
Fixes no issues that i know of.
This has no behaviour changes, so it doesn't need testing, as it only affects borderline cases.

Fix a typo in a registry key.

---

src/dialogs/generic.py

Fixed error `gi.RepositoryError: Requiring namespace 'Gtk' version '4.0', but '3.0' is already loaded` with [this package](https://archlinux.org/packages/extra/x86_64/gtksourceview4/)
Fixes https://aur.archlinux.org/packages/bottles/#comment-850104

[Fix] GTK Namespace

---

src/backend/dlls/dll.py

<details>
<summary>Bottles throws an exception when trying to enable DXVK for 32 bit prefixes with the following error log:</summary>
```
(18:11:56) INFO Setting Key: [dxvk] to [True] for bottle: [x32]… 
(18:11:56) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [d3d9] and Data: [native,builtin] in x32 registry 
(18:11:57) INFO Using WINE Registry CLI 
(18:11:57) INFO reg: The operation completed successfully
(18:11:57) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with Value: [d3d10] and Data: [native,builtin] in x32 registry 
(18:11:58) INFO Using WINE debug tool 
(18:11:58) INFO Using WINE Registry CLI 
(18:11:58) INFO reg: The operation completed successfully
(18:11:58) INFO Adding Key: [HKEY_CURRENT_USER\Software\Wine\DllOverrides] with …
```

Fix `DLLComponent` installation for 32 bit prefixes

---

com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml

Bundle samba and its dependencies (rpcsv-proto and parse-yapp) with flatpak.
A lot of the tools that the Samba suite provides, such as winbind, ntlm_auth, etc. are needed when running certain applications.
Fixes #1001
[ntlm_auth](https://www.samba.org/samba/docs/current/man-html/ntlm_auth.1.html) is part of the [samba](https://www.samba.org/samba/docs/current/man-html/samba.7.html) suite. This PR bundles samba and its required dependencies with flatpak.  Resources I used that helped me with bundling Samba:
- [Samba Wiki](https://wiki.samba.org/index.php/Build_Samba_from_Source)
- [gnome control center](https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/build-aux/flatpak/org.gnome.Settings.json)
- [Dolphin](https://github.com/flathub/org.kde.dolphin/blob/master/org.kde.dolphi …

add samba, rpcsvc-proto, parse-yapp  dependencies to flatpak

---

com.usebottles.bottles.dev.json
data/com.usebottles.bottles.desktop.in
snapcraft.yaml
src/main.py
src/window.py

This is more sandbox friendly and does not require and extra library.
We also add X-GNOME-UsesNotifications=true so that GNOME Software and
similar can pick this piece of metainfo.
Ill test in a bit.

Use GNotification instead of libnotify

---

src/backend/utils/terminal.py

Add foot as a terminal option 
Fixes #1110
Pressing "Command line" now opens a foot terminal if foot is present.

Add foot as a terminal option

---

src/backend/wine/executor.py
src/window.py

Fixes a race condition as described in #1104 by forcing programs launched using the CLI `-e` and `-b` parameters to run using WINE Start instead of being launched asynchronously. The WINE Start subprocess returns once the application is launched, so we can simply wait for it.
Fixes #1104
- Bug fix (non-breaking change which fixes an issue)

Temporary fix for #1104

---

src/dialogs/generic.py
src/window.py

Fixes the "Close" button of AboutDialog doesn't close the dialog. This also hides the "License" button which does nothing too (widgets in GTK+3 are invisible by default, and using `Gtk.Dialog.run()` instead of `show_all()` results this).
This PR was created by referring this page: https://stackoverflow.com/questions/577354/glade-aboutdialog-doesnt-close.
I'm sorry if something wrong because this is the first time I write code in PyGTK and I'm not sure anything about that (though I'm a little familiar with GTK in Vala).

Destroy AboutDialog on clicking the Close button

---

CODE_OF_CONDUCT.md
CONTACT.md

The Code Of Conduct called CONTACT.md was too generic and can't be considered a Code Of Conduct.

Update Code Of Conduct using common standards

---

src/backend/utils/generic.py

Improve version sorting in generic and add sorting via pattern.
Fix small typos:
For line 100 because there are nothing return when version < '2.32'
<details>
<summary>Test A</summary>
```python
from generic import sort_by_version
assert sort_by_version(
["dxvk-1.9.2", "dxvk-1.9.4", "dxvk-1.9.1", "dxvk-async-1.9.4", "dxvk-1.10"]
) == ['dxvk-1.10', 'dxvk-1.9.4', 'dxvk-1.9.2', 'dxvk-1.9.1', 'dxvk-async-1.9.4']
```
</details>

Improve version sorting

---

src/backend/managers/component.py
src/backend/utils/file.py

This contributes to my problem of not being able to download any files - winebridge, runners, dxvk, etc.
For details on why stuff has been made, check out the commit messages!
Helps to debug: #1220
Not all at the moment. Need instructions on how to run Bottles from source.

 Adding more logging to download process plus some code cleanups

---

src/backend/utils/manager.py

- Glob search for existing desktop files matching with the exclusion of timestamp.
- Remove said files before creating a new one.
Fixes #1315
- [x ] New feature (non-breaking change which adds functionality)
- Created a few desktop files before the change
- Pressed "Add desktop entry" and observed only one new file
- Pressed it more times and observed the timestamp updating each time

#1315 update desktop entries 

---

src/views/bottle_details.py

The default for running an executable should be the bottle container, for flatpak sandboxed environments. This change makes more sense than the default location for the operating system as the user can quickly navigate to another folder easily, but cannot find the bottle folder easily.
Fixes #(issue)
None
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Tested on Fedora Silverblue through Toolbox

Adding support to run executable from bottle container drive by default

---

src/backend/managers/steam.py

Fixes #1274
- Launched `bottles` on a direct-from-Git install, apps which couldn't be scanned before now show up on the bottles list.
- Please test on Flatpak, Steam imports appeared to work before my fix on there.

Fixed Steam apps scanning on non-Flatpak systems

---

com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml

This PR updates Samba to version 4.15.6 on the Flatpak build manifests
Fixes #1347

[flatpak] deps: update samba to 4.15.6

---

src/backend/utils/terminal.py

Changed xterm handling to be more like other terminals. The difference seems to mostly be in quotation marks.
Fixes #1330 
- Ran the changed code and tried using the Command Line utility. Utility pops up with wine cmd active and is close-able with Ctrl+C or by clicking the X in the title bar.

Actually fix #1330: Fix xterm handling in cmd execution

---

src/backend/utils/manager.py

There are many cases where the bottle name and path are not the same. Launching a bottle with CLI requires the bottle path not the bottles name. It only works in the case where they are equal.
Fixes #1392  #1325
- [ *] Bug fix (non-breaking change which fixes an issue)
*    Create a bottle
*    Install an application
*    Change bottle name
*    Create a desktop entry
*    Click new desktop entry in the DE menu
*    Check that application launches correctly

Change bottle-cli command to use Path

---

src/ui/details-bottle.ui

* Changed halign on entry_name to fill which is the default and therefore the XML element is removed.
* Increased title lenght to 128 characters from 20. This only affects editing.
Fixes  #1390
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* Create a bottle with a really long name e.g. 128 characters.
* Observe that the title now fill the parent container, but also doesn't exceed its parent. Instead the title can be scrolled to view it in entirety.
* Try to edit the title and notice that it works as expected.

Add horizontal fill to bottle title and set max lenght 128

---

debian/control
po/bottles.pot
src/backend/managers/manager.py
src/backend/runner.py
src/backend/wine/cmd.py
src/backend/wine/control.py
src/backend/wine/executor.py
src/backend/wine/explorer.py
src/backend/wine/msiexec.py
src/backend/wine/net.py
src/backend/wine/reg.py
src/backend/wine/regedit.py
src/backend/wine/start.py
src/backend/wine/taskmgr.py
src/backend/wine/uninstaller.py
src/backend/wine/wineboot.py
src/backend/wine/winebridge.py
src/backend/wine/winecfg.py
src/backend/wine/winedbg.py
src/backend/wine/winepath.py
src/backend/wine/wineserver.py
src/cli.in
src/views/bottle_preferences.py

"WINE" is incorrectly spelled, as it should be "Wine", per https://www.winehq.org/
Continuation of the broken PR https://github.com/bottlesdevs/Bottles/pull/1407.
Untested.

Fix "WINE" typo

---

data/com.usebottles.bottles.appdata.xml.in

Bottles versioning is no longer in experimental status.
(According to this: fcc3f5d0531b02b7de3f6fbe5a9880c24195ef43)

Changing the status of bottles versioning

---

data/com.usebottles.bottles.appdata.xml.in

See the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-mimetypes) for reference

Replace deprecated <mimetypes> tag in metainfo

---

po/LINGUAS
po/zh_CN.po
po/zh_HK.po
po/zh_SG.po
po/zh_TW.po

This will allow users with LANGUAGE=zh_CN/zh_SG/zh_HK/zh_TW to see the correct translation.
Create symlinks to `zh_Hans` or `zh_Hant` for language codes `zh_CN` / `zh_SG` / `zh_HK` / `zh_TW` so that distributions using these language codes load translation files normally.
Fixes https://github.com/bottlesdevs/Bottles/issues/574
Existing Chinese translations for Bottles cannot be found for distros using the `zh_CN` / `zh_SG` / `zh_HK` / `zh_TW` language codes.
```
LANGUAGE=zh_Hans flatpak run com.usebottles.bottles
LANGUAGE=zh_Hant flatpak run com.usebottles.bottles
LANGUAGE=zh_CN flatpak run com.usebottles.bottles
LANGUAGE=zh_SG flatpak run com.usebottles.bottles
LANGUAGE=zh_HK flatpak …
```

i18n: add regional variants of Chinese as symbolic links

---

.vscode/settings.json
src/ui/details.ui
src/views/details.py

In the details screen, the title buttons were **always** displayed in the content pane. This is not a problem with GNOME's default decoration layout (`appmenu:close`), but in DEs like elementary or KDE, this brings an appearance that is perhaps not as expected:
This PR allows any controls that need to be displayed in the sidebar panel to do so seamlessly:

details: fix title buttons position

---

src/backend/utils/terminal.py

Until [XDG Terminal Intent](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/46) specification is widely supported, we can only guess what terminal emulator the user prefers.
Let’s look for third-party programs first, since those had to be installed explicitly by the user, and xterm last, as it tends to be present as a fallback.

Improve terminal emulator priorities

---

src/ui/details-preferences.ui
src/ui/dialog-gamescope.ui

This MR adds some minor improvements for Gamescope.
First, GtkSwitch and GtkButton are switched:
Second, "Use integer scaling" can be toggled by simply pressing on the row.
In accordance of:
- https://github.com/bottlesdevs/Bottles/pull/1668#discussion_r904771073
- https://github.com/bottlesdevs/Bottles/pull/1668#discussion_r904763987

Minor Gamescope improvements

---

src/backend/wine/winecommand.py

gamescope crashes with some Vulkan layers like MangoHud. With this change, MangoHud isn't applied to gamescope, but called within gamescope and applied only to the program executing inside it.
This gives us at least working MangoHud within gamescope until #1437 can be done

Fix gamescope with MangoHud

---

src/views/bottle_preferences.py

This MR disables configuring Gamescope when it's unavailable:

Disable Gamescope settings when unavailable

---

po/LINGUAS

Add `zh_CN`/`zh_HK`/`zh_SG`/`zh_TW` back to `LINGUAS`, so that the Chinese translation can be used by actual users.
Fixes #1692
See https://github.com/bottlesdevs/Bottles/issues/1692 and https://github.com/bottlesdevs/Bottles/pull/1515.

i18n: Fix Chinese translation not available (#1692)

---

src/views/bottle_preferences.py

Having just a check of the "proton" string in the runner name is insufficient to know if this is actually a Proton runner or not since the Wine-GE release is actually called `wine-lutris-GE-Proton7-20-x86_64`.
Other quick win solution:
Ignoring if "wine" or "lutris" is found in the runner's name.
The probably better solution:
Checking inside the runner folder for some files that are only found in Proton runners.
I tested this regex against the current naming conventions I'm aware of with a simple Python script (I haven't tried to run a build of Bottles yet):
```
GE-Proton7-24
Proton 7.0
Proton - Experimental
wine-lutris-GE-Proton7-20-x86_64
```

Avoid alerting when using Wine-GE-Custom

---

src/dialogs/installer.py
src/ui/dialog-installer.ui

Slightly tweak the UI of the second page in the new installer screen:
- Add icon of the app being installed
- space progress bar and progress bar text
- Navigate to changed UI
- check if UI displays correctly 
- check if UI works correctly
- check if installation works correctly

tweak new installer screen

---

src/ui/dialog-drives.ui
src/ui/dialog-env-vars.ui

Upon pressing Escape, dialogs should close.
Related to https://github.com/bottlesdevs/Bottles/issues/1598.

Add `window.close` action for dialogs

---

com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml
src/window.py

- Bump libadwaita dependency in Flatpak manifest
This fixes the regression to https://github.com/bottlesdevs/Bottles/commit/ed67dd8a84e3e2b781b6d7c7e6e44203c8d0f0df after we switched to libadwaita.

Use AdwMessageDialog for custom Bottles path error

---

src/dialogs/generic.py
src/ui/about.ui

This replaces the old GtkAboutDialog with the new AdwAboutWindow released in the new libadwaita 1.2 release
- open new about window
- verify that all links are correct and clickable

Add new AdwAboutWindow

---

src/dialogs/generic.py
src/ui/about.ui

When pressing esc on the new About window to close it bottles instead segfaulted, this commit fixes it
- open about dialog
- press `esc`
- window closes without any segfault
- repeat multiple times to make sure it works consistently

Fix segfault when pressing esc on about window

---

src/dialogs/generic.py
src/ui/about.ui
src/window.py

Don't depend on template for about window anymore, since AdwAboutWindow
is a final class and doesn't support using it as a template.
- navigade to about window
- go through each section, make sure everything displays properly
- test if pressing `esc` crashes bottles

Implement about window properly

---

src/ui/details-bottle.ui

Currently the dropdown for launch options had bad/no padding for the recently launched applications:
This is how it looks with this pr:
- Navigate to new menu
- Verify UI changes
- Verify that buttons still work

Fix padding in launch option menu

---

src/dialogs/onboard.py
src/ui/onboard.ui

This stops the user from skipping the onboarding.
Fixes #1803 
- remove bottles data directory
- open bottles
- try to skip onboard, doesn't work
- complete onboarding as intended, works without any issues

Stop user from skipping onboard dialog

---

src/ui/window.ui
src/window.py

This moves the health check to the About window (About -> troubleshooting -> Debugging information)
- open about dialog
- go to debugging information
- check if health check appears properly
The way to get to the health check changes, so the github bug report template will have to be updated to reflect this change.

move health check to about window

---

src/ui/new.ui
src/utils/gtk.py

The user currently is able to create bottles with empty names or names only consisting of spaces, this shouldn't be possible
- Try to create bottle with empty name, fails
- Try to only fill bottle name with tabs or spaces, fails

Don't allow user to create empty bottle names

---

com.usebottles.bottles.dev.yml
src/ui/library-entry.ui
src/views/library.py
src/widgets/library.py

The color of the menu button for library entries now adjusts after the
thumbnail image of the game, to make a better contrast
- Add games to library
- Check if menu button adjusts to game thumbnail
- switch between dark/light mode to see if the menu buttons are affected

Improve library menu button

---

src/views/library.py

This stops bottles from adding invalid css classes to buttons which causes them to loose the color they're supposed to have, causing it to potentially have bad contrast with the thumbnail.
- Go to library view
- check if menu button for library entry (in this case notepad++) has bad contrast

Fix invalid css issue for library menu buttons

---

src/ui/preferences.ui
src/views/preferences.py

Adds a dark mode switcher on systems that do not support color preference. Fixes #1758

Add dark mode switch as fallback

---

README.md

Since we let go of the AUR package, let's stop mentioning it as an official package.
Proposal: I think we should stop mentioning unofficial packages altogether. Flatpak is officially maintained and always in the latest version. Users typically get a subpar experience with distro packages because they have to deal with outdated libs, overlooked dependencies, etc. and may stop using the app and come up with the wrong conclusion.
All in favor? @mirkobrombin @jannuary @axtloss

Remove mention of AUR and unofficial packages

---

README.md

Removes reference to a table of third party packages not in the readme anymore

Remove reference to removed packages table

---

com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml
src/backend/globals.py
src/backend/models/samples.py
src/backend/runner.py
src/backend/wine/winecommand.py
src/dialogs/meson.build
src/dialogs/vmtouch.py
src/ui/bottles.gresource.xml
src/ui/details-preferences.ui
src/ui/dialog-vmtouch.ui
src/views/bottle_preferences.py

This allows bottles to preload files into cache before starting the application, causing faster loading times in games and applications.
Fixes #1329 
---
Currently I only have the actual precaching implemented, freeing the cache after the application quits isn't yet implemented and the ui probably needs some tweaks too.

Add file preloading/caching 

---

bottles/backend/managers/dependency.py

The old code tried to copy the dll's over themselves (giving a `SameFileError`) because `_path` and `_dest` would be the same.
Fixes #(issue)
https://github.com/bottlesdevs/dependencies/issues/120
Installing dependencies `d3dcompiler_43`, `d3dcompiler_47`, `d3dx9`, and `d3dx11` now works properly.

Bugfix glob file copy_dll

---

bottles/frontend/ui/details-bottle.ui

"Legacy Tools" renamed to "Legacy Wine Tools".
Item subtitles removed.
Fixes #1945 
No tests

Simplification of "Legacy Tools" section

---

bottles/frontend/ui/preferences.ui

The dark mode switch should be invisible by default as to not appear on systems with color scheme preference.

Revert "make switch_theme visible"

---

bottles/frontend/windows/main_window.py
data/com.usebottles.bottles.gschema.xml

Quoting the commit message
```
It makes sense to start the application in the main view where it was
closed. For example, it is plausible that most users set up their
bottles once and then want to land directly in the library view after
launch.
This behavior is also known from other programs such as web browsers or
GNOME Calendar, and it seems that Bottles once handled it this way in
the past. Therefore the gsettings key `startup-view` has now been
(re)activated and represents the last selected view in the main window.
```
- Manually, by building Bottles and testing the changes

Remember last used view in topmost `AdwViewStack`

---

bottles/meson.build
meson.build

Bump meson version to 0.59, the latest installed in gnome runtime 42. It obsoletes the post_install.py script by using a function from the gnome module in meson. Inspired by https://gitlab.gnome.org/GNOME/gnome-sound-recorder/-/merge_requests/192
Should the post_install.py script be removed?

build: Depend on Meson 0.59

---

bottles/backend/wine/winecommand.py
com.usebottles.bottles.dev.json
com.usebottles.bottles.dev.yml

It accommodates both 64-bit and 32-bit programs with caveat that
32-bit users will be seeing benign gstreamer warnings.
Set the GST_PLUGIN_SYSTEM_PATH variable in flatpak manifests in a way that accomodates both 64-bit and 32-bit programs. This reduces a bit the flatpak work-arounds that we have in the app. The lutris flatpak sets this variable this way, so you could say it is already tested plus was worked on by @TheEvilSkeleton 
Fixes #2023 

Set GST_PLUGIN_SYSTEM_PATH in flatpak manifest

---

bottles/frontend/ui/window.blp
bottles/frontend/windows/main_window.py

Adds a view switcher bar when the app goes into the mobile layout. Fixes #2085
https://user-images.githubusercontent.com/31619874/190927156-d927bc7c-eb2e-44be-acb7-9c11ed3e01d3.mp4

frontend: Implement `AdwViewSwitcherBar` for the main window

---

bottles/frontend/ui/dialog-gamescope.blp
bottles/frontend/windows/gamescope.py

Use `SpinButton`s to give a better indication that numbers go in entries. When using nonintegers, SpinButton automatically sets to "0".

frontend: Improve Gamescope dialog

---

bottles/frontend/ui/details-preferences.blp

I was looking for a way to change the runner easily a while ago, and missed this option. This would make it more visible, and with a note, so that the user doesn't accidentally miss it.

Updates the Components section of the Bottle Preferences

---

bottles/backend/wine/executor.py

I've encountered with a bug when adding a Program via the plus icon. If the program is run right after being created, an error is thrown because the dictionary doesn't contain the `arguments` key.
I'm not sure if this is expected or if the dict should contain the key with an empty string.
Restarting Bottles and running the program seems to provide these defaults so it works ok after a restart.
What I did in the PR is to safely access the dictionary values and provide a default when they don't exist, which fixes the issue.

Safely access `program` "dict" keys

---

.vscode/settings.json
bottles/frontend/ui/preferences.blp
bottles/frontend/views/preferences.py

This commit adds support for using portals to set the Bottles Directory
This PR should let the Bottles Directory option in the preferences use portals in Flatpak (so you can actually use custom paths in the flatpak version).
Please describe the tests that you ran to verify your changes.
- Compile the Bottles Flatpak and install it
- Go into preferences and select a folder. A portal should show up
- select a folder and click on it
- your path should be /run/user/1000/doc/xdg/portal/stuff/foldername. this means xdg-document-portal is working and is giving the flatpak persistent access to the folder.
- try rebooting
it …

Use portal for setting the Bottles Directory

---

bottles/backend/wine/winecommand.py

Fix Gamescope incorrectly being passed the apps' arguments. Fixes #2165.

backend: Fix Gamescope arguments

---

bottles/backend/dlls/dxvk.py

Removes the use of `d3d10.dll` & `d3d10_1.dll` that are shipped along with dxvk. They are helper libraries while the main Direct3D 10 implementation is in `d3d10core.dll`.
They were never fully implemented and aren't installed by default in the official dxvk setup script or in Steam Proton. The devs recommend using wine's own as they work better and are more complete. (The Windows versions also work)
Fixes usage of dxvk 2.0.0 when it releases since these dll's will have been removed. Also allows using current dxvk master if you want to. 
I wanted to test with dxvk master and so put it in bottles dxvk directory. But i found it wouldn't work and bottles errored on startup. Had to modify `dxvk.py` and remove these dll's from the managed list.

backend: Don't use d3d10 & d3d10_1 dll's from dxvk

---

bottles/frontend/windows/installer.py

* Fixes error: `AttributeError: 'DetailsView' object has no attribute 'update_programs'.`
* Fixes navigation back to bottle view on installer completion

Fix installer completion

---

bottles/backend/wine/winecommand.py

Hello!
Recently I've encountered with a very weird bug when running a program in Terminal mode vs Non terminal mode.
When running with the regular mode, after a while the program would hang and I would have to force close. Surprisingly enough, running with the terminal mode (the one that runs easyterm.py), everything was going ok.
After some debugging I found that the culprit was the call to `proc.wait()` in `winecommand.py`. In the Python docs there is a note regarding the mix of `proc.wait()` and the stdout PIPE. After the process generates enough output, it will deadlock. On my tests, removing the `wait` works as expected.
The wait call was introduced in this commit https://github.com/bottlesdevs/Bottles/commit/942f18d5534572ca916513090de936d24d710467
Given that `proc.communicate()` is …

Fix deadlock of Popen.wait

---

bottles/frontend/windows/drives.py

This enables portals for drive selection to allow directories outside of the sandbox. It also renames the title.
Closes https://github.com/bottlesdevs/Bottles/issues/2251.

frontend: Minor improvements for drive selection

---

bottles/backend/wine/winecommand.py
bottles/frontend/views/bottle_preferences.py

Here is a fix for Latency flex.
First, the function to disable it was not called correctly, resulting in the fact that LatencyFlex was never disabling itself after it was enabled once.
Other fix is that the `VK_ICD_FILENAMES` was not set correctly: currently, it would only be assigned to the LatencyFlex JSON, so it would not have the JSON for the GPU, making games crash at launch. This fixes the issue by changing all the `env.add()` of the variable `VK_ICD_FILENAMES` to `env.concat()`. That way, no code is overwriting the variable, and the games load correctly.

Fix Latencyflex not disabling correctly and environment variables

---

bottles/backend/managers/manager.py

Fixes start-up error caused by space in bottle name
Fixes #(issue)
Bottle name is "ov2 backup ", and it caused this error on next startup:
Error while running async job: <function MainWindow.__on_start.<locals>.get_manager at 0x.....>
Exception: [Errno 2] No such file or directory: '/...../.local/share/bottles/bottles/ov2 backup /bottle.yml'
- Bug fix (non-breaking change which fixes an issue)

Fix bottle name space error

---

bottles/backend/wine/winecommand.py

This PR makes 2 changes:
1.  If WINEDLLOVERRIDES environment variable defined in bottle's settings, it is added to final list of DLL overrides which is passed to wine.
2.  MSHTML can be enabled now through bottle's settings interface (DLL Overrides or Environment Variables), when it's needed to some apps.

Fixed setup of dll overrides on bottle start

---

bottles/backend/utils/manager.py
bottles/frontend/cli/cli.in

E.g.
```
bottles-cli run -b bottle -e x.exe arg1 arg2
bottles-cli run -b bottle -e x.exe -- --arg1=val arg2
```
Fixes https://github.com/bottlesdevs/Bottles/issues/2305
Will break expected functionality: `--args` now not expected
if program X launched with default arguments `defargs`:
```
bottles-cli run -b bottle -p X arg1 arg2
x defargs arg1 arg2
bottles-cli run -b bottle -p X --args-replace arg1 arg2
x arg1 arg2
```
.desktop file now listen for new arguments
Allow something like this:
```
xdg-mime default bottle--telegram--1111.1111.desktop x-scheme-handler/tg
xdg-open tg://settings # will open installed in bottles telegram settings # NB: not checked
```
Just check it works in separate python file :(

frontend/cli: run: Allow multiple arguments to pass to executable

---

bottles/frontend/views/bottle_preferences.py

Previously, the check_entry_name method was not called when renaming a bottle, meaning valid_name wasn't set and bottles could not be renamed.  
Fixes #2304

Fix bottle renaming

---

bottles/backend/managers/component.py
bottles/backend/managers/manager.py

My internet sucks, manifest fetching and file download randomly failed.
when `ComponentManager.install()` failed with downloading, it won't pop the failed installation from `self.__queue`, next call to `ComponentManager.install()` will keep waiting for empty queue forever.
then Onboard Dialog will stuck at "Almost Done" forever.

fix: ComponentManager.install() deadlock

---

bottles/backend/managers/dependency.py
bottles/backend/utils/generic.py
bottles/backend/wine/reg.py
bottles/backend/wine/regkeys.py

In previous implementation, `replace_font` calls `Reg.add()`, invoke `reg.exe add ...` for each font replacement entry, which is extremely slow for large replacement set since every `reg.exe` call will take several seconds to complete.
This PR will add a new `Reg.bulk_add()` for bulk registry importing support.

fix: slow replace_font

---

bottles/backend/managers/installer.py

Supports `userdir/` placeholder for `__perform_checks` (backend/managers/installer).

feat: support userdir/ placeholder for installers checks

---

bottles/backend/managers/manager.py
bottles/backend/models/result.py
bottles/frontend/windows/onboard.py

There is a index out of range bug at:
https://github.com/bottlesdevs/Bottles/blob/5933056003cb5d80c4e1c85ed9d874f7260cd4ed/bottles/backend/managers/manager.py#L882-L912
when user have a bad network, `self.dxvk_available`, `self.vkd3d_available`, `self.nvapi_available` will be empty.
But I suddenly realize the reason for this bug is making proper initialization a prerequisite, and there may be more bugs like this, so I choose to fix this issue by ensuring the onboard initialization will complete properly, instead of skip component download and show onboard dialog to user on every startup. 

fix: onboard dialog shows "All ready" when not ready

---

bottles/backend/models/samples.py

Enables VKD3D by default when creating a Bottle with the gaming environment, as most games releasing currently are made under DX12 and without, games won't launch properly.
- Locally

feat: enable VKD3D in the Gaming environment

---

bottles/backend/wine/winecommand.py

Before, Bottles would set `GST_PLUGIN_SYSTEM_PATH` regardless if GStreamer was bundled in the runner. If it is not, then the environment variable would be set to an empty string, which according to [the documentation](https://gstreamer.freedesktop.org/documentation/gstreamer/running.html?gi-language=c):
> Setting this variable to an empty string will cause GStreamer not to scan any system paths at all for plug-ins.
I attempted to see "Star Wars Jedi: Fallen Order" (EA App) intro video.
Before the change, it wouldn't play when using Wine Soda. It would play on system Wine (which has GStreamer bundled), or if `BOTTLES_USE_SYSTEM_GSTREAMER` was set.
After the change, the video plays on Wine Soda without any intervention.
Tested on Linux NixOS unstable (not the Flatpak package)

Don't override `GST_PLUGIN_SYSTEM_PATH` if runner doesn't bundle GStreamer

---

bottles/frontend/views/bottle_details.py

The problem was that update_programs() wait for arguments, and if used in a callback to RunAsync, it will receive the wrong arguments. 
Fixes properly #2377
Locally

fix: wrong call to update_programs()

---

bottles/backend/managers/dependency.py

It is not used currently, but using action `cab_extract` in dependencies on local files is not working because the destination isn't provided. This PR adds the destination argument so that it works properly.
Fixes nothing for now

fix: add dest to cabextract on local files

---

bottles/backend/downloader.py

This change is just QoL, it was annoying when the terminal was to small and we download a component, it will spam the download bar. Now it changes the size dynamically, making it harder (but not impossible) to have spamming in the term.

term-ui: dynamic length of progress bar according to terminal size

---

bottles/backend/managers/dependency.py

Fixes a bug in "patoolib" that does not extract .tar.xz files correctly if you have xz or 7z installed in your system.
Also added a check to return False when a source DLL is being copied to the wine prefix and the source file does not exist. 
Fixes https://github.com/bottlesdevs/Bottles/issues/2491
To reproduce, install xz or 7z in your distro.

Addresses bug from patoolib

---

bottles/frontend/views/bottle_preferences.py

Too many queue.add_task and queue.end_task
Fixes #2522

fix: broken back button if DXVK and VKD3D are disabled

---

bottles/frontend/views/bottle_preferences.py

If DXVK is disabled and VKD3D wants to be enabled, it will also enable DXVK. If DXVK wants to be disabled and VKD3D is enabled, then it will disable VKD3D.
Fixes #2427

ui: Make VKD3D not enable-able without DXVK

---

bottles/backend/managers/dependency.py

This improves the installation time a lot for certain dependencies (looking at you faudio with your 34 DLLs)

backend: Add `import_bundle` on dependency installation

---

bottles/backend/wine/winecommand.py
com.usebottles.bottles.yml

When using a runner that provides GST plugins, depending on the distro those errors can happen:
```
(wine:2356): GStreamer-WARNING **: 00:08:05.072: Failed to load plugin '/home/USER/.var/app/com.usebottles.bottles/data/bottles/runners/wine-ge-proton7-35/lib64/gstreamer-1.0/libgsthls.so': libnettle.so.6: cannot open shared object file: No such file or directory
(wine:2356): GStreamer-WARNING **: 00:08:05.140: Failed to load plugin '/home/USER/.var/app/com.usebottles.bottles/data/bottles/runners/wine-ge-proton7-35/lib64/gstreamer-1.0/libgstbz2.so': libbz2.so.1.0: cannot open shared object file: No such file or directory
(wine:2356): GStreamer-WARNING **: 00:08:05.151: Failed to load plugin '/home/USER/.var/app/com.usebottles.bottles/data/bottles/runners/wine-ge-proton7-35/lib64/gstreamer-1. …
```

fix: Add runner libs to fix embedded GStreamer not finding them

---

bottles/backend/managers/manager.py
bottles/frontend/views/bottle_preferences.py

Renaming a bottle breaks library entries as the library.yml wasn't updated. Now, the changes correctly updates the library config file, and also properly update the bottles list in manager.py.
Fixes #2490 

fix: update library entries when renaming a bottle

---

bottles/backend/utils/gpu.py
bottles/backend/utils/nvidia.py
bottles/frontend/views/bottle_preferences.py

This fixes the critical (but benign) error when starting Bottles without a Nvidia 

fix: critical error when not using a Nvidia GPU

---

bottles/backend/managers/library.py
bottles/backend/managers/manager.py
bottles/frontend/views/bottle_preferences.py
bottles/frontend/views/library.py
bottles/frontend/widgets/library.py
bottles/frontend/widgets/program.py

- if the bottle was deleted but the library entry remains, delete it
- if images are missing, redownload them if they were present
- deleting a bottle now deletes the library entry to avoid empty grey entries
- Renaming a program renames the library entry and redownloads a cover
---
- Fixes #2416 
- Fixes #2354
- Fixes #2511
- Fixes #2490
- Fixes #2386

frontend: Fix various library crashes and empty library items

---

.github/workflows/close-issues.yml

It could be improved by checking the actual shipped version of Bottles, and closing if it's too old.

Add GitHub Action close issues if people are using a too old version

---

bottles/backend/utils/generic.py

Current implementation of `generic.detect_encoding()` use a guess list to detect text encoding
which will break all codecs which use similar encoding method to the codec ordered before it
affect `WineCommand` output log afaik
For example:
- `codepage 936` use by Wine by default when setting language to Simplified Chinese, which is actually `gb2312`/`gbk` in different Windows version
- `gb2312` use one or two bytes for encoding
- `utf-16` use two bytes for encoding
- they use different codepoint table
- `utf-16` ordered before `gb2312` in guess list
- `gb2312` encoded bytes will be matched as `utf-16`
then garbled text happened:
```Python
>>> '你好'.encode('gb2312').decode('utf-16')
'\ue3c4쎺'
```
or
```Python
>>> 'こんにちは'.encode('euc-jp').decode('utf-16')
'뎤\uf3a4쮤솤쾤'
```
This PR replaced the …

fix incorrect text codec detection

---

.github/ISSUE_TEMPLATE/bug.yml

This adds information to use health check for those who are unable to launch Bottles.
Related to https://github.com/bottlesdevs/Bottles/issues/2637#issuecomment-1409679514

misc: Add information using bottles-cli

---

bottles/backend/dlls/dll.py
bottles/backend/managers/manager.py
bottles/backend/models/config.py
bottles/backend/wine/reg.py

For some reasons, sometimes NVAPI wants to be installed even though the user doesn't have an Nvidia GPU. This PR adds another check to see if a DLL exists before check/install/uninstall. Also, a check to see if the user has a Nvidia card when creating a Bottle was implemented. This does not fix all occurences of the behavior, like for example when importing an existing Bottle, but it's a start. 
Fixes #2594
For reviewers to test: when not using a Nvidia card, create a bottle. You should not have any indication of NVAPI being installed.

fix: Create bottle crashing if no Nvidia GPU and NVAPI installs

---

bottles/frontend/ui/window.blp
po/POTFILES

This updates entries in POTFILES, which caused errors during translation building. It also makes the "Main Menu" tooltip translatable.
```sh
meson /tmp/translation-build
meson compile -C /tmp/translation-build bottles-pot
meson compile -C /tmp/translation-build bottles-update-po
```

Update translation files

---

bottles/backend/logger.py
bottles/backend/utils/generic.py
bottles/backend/wine/winecommand.py

cheery pick from `decoupled-backend` branch
fixed `WineCommand.run()` returning `bytes` when stdout result is empty(which introduced in https://github.com/bottlesdevs/Bottles/pull/2585), then logger will crash because of this.
any feature using `WineCommand` are working now

fix inconsistent return type for WineCommand

---

bottles/frontend/ui/details-bottle.blp
bottles/frontend/ui/library-entry.blp

Ellipsizes or wraps long names when there's no space:
Fixes #2670

frontend: Gracefully handle ridiculous names

---

bottles/backend/downloader.py

when user is using locale with legacy encoding, like `*.iso8859-1`, `POSIX`, `C`
the encoding which terminal will use won't cover unicode codepoint space
then the download progress char `━` will failed to print
Fixes #2017 
Fixes #2601 
Fixes #2659 
although this fix provide better compatibility to systems that is still using legacy encoding
we still should encourage users to use `utf-8` to make the world better.
Not tested yet

fix terminal download progress crash

---

bottles/backend/managers/manager.py
bottles/backend/runner.py

`wine-ge-proton` contains `proton` in its name, which caused Bottles to enable the Steam Runtime.

Don't enable Steam Runtime when switching to `wine-ge-proton`

---

bottles/backend/managers/dependency.py
bottles/frontend/widgets/dependency.py

Fix duplicate item in `BottleConfig.Installed_Dependencies` after reinstall any dependency

fix: duplicate installed dependencies after reinstall

---

bottles/backend/managers/conf.py
bottles/backend/managers/epicgamesstore.py
bottles/backend/managers/origin.py
bottles/backend/managers/ubisoftconnect.py
bottles/backend/models/config.py
bottles/backend/utils/json.py
bottles/backend/utils/meson.build
bottles/backend/utils/yaml.py
bottles/backend/wine/register.py
bottles/frontend/cli/cli.py
bottles/frontend/windows/crash.py

Fix bug reported by Slowpokefarm@Discord
```
(1)(deck@steamdeck ~)$ flatpak run --command=bottles-cli com.usebottles.bottles -j list bottles
(process:2): Gtk-WARNING **: 13:46:18.764: Locale not supported by C library.
Using the fallback 'C' locale.
Traceback (most recent call last):
File "/app/bin/bottles-cli", line 657, in <module>
cli = CLI()
File "/app/bin/bottles-cli", line 151, in __init__
self.__process_args()
File "/app/bin/bottles-cli", line 170, in __process_args
self.list_bottles(c_filter=_filter)
File "/app/bin/bottles-cli", line 237, in list_bottles
sys.stdout.write(json.dumps(bottles))
File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, …
```

make BottleConfig Json serializable

---

bottles/frontend/ui/list.blp

This renames the blue button to "Create New Bottle…", to keep it consistent with the dialog and `+` button at the top left.

frontend: Rename create bottle button in list

---

bottles/frontend/ui/window.blp
bottles/frontend/windows/main_window.py
data/com.usebottles.bottles.gschema.xml

Main window will now remain the same size as it was before closing.
There already was fields in gschema but unused for some reason
Tested by @TheEvilSkeleton

Make window remember dimensions

---

bottles/frontend/ui/details-bottle.blp
bottles/frontend/ui/dialog-installer.blp
bottles/frontend/ui/style.css
bottles/frontend/views/bottle_details.py
bottles/frontend/windows/installer.py

Removes the silly code adding styles and bundles them in CSS instead, has a sideeffect of not causing a crash on GTK 4.10
Fixes #2788

frontend: Fix applying style classes

---

bottles/backend/managers/steam.py

fix: Steam shortcut uses Bottle's path instead of name

---

bottles/frontend/ui/preferences.blp

This uses the same icon used in Fractal for the General page:
Fractal:

Change General icon and extern syntax

---

.github/workflows/build_flatpak.yml
.github/workflows/pylint-checker.yml
.github/workflows/pylint-commenter.yml

I bumped the versions of actions checkout, flatpak builder and its gnome version to 44.

workflows/*: Bump version of actions

---

bottles/frontend/ui/library-entry.blp
bottles/frontend/ui/library.blp
bottles/frontend/views/library.py

Fixed "no cover" text not being shown
Centered items in LibraryView, I think it's look better, but if you don't agree, I can revert this
Fixes https://github.com/bottlesdevs/Bottles/issues/2458
I dont know how to test it tbh...

Minor improvements and fixes to library

---

bottles/backend/dlls/dll.py
bottles/backend/dlls/vkd3d.py
bottles/backend/wine/executor.py

Newer vkd3d-proton will include a new dll : `d3d12core.dll`.
The `d3d12.dll` now being a wrapper around this new dll, reference: https://github.com/HansKristian-Work/vkd3d-proton/commit/fbf03829ebaaf068f9166c668a7f1c9265999915
Additionally, I found why `del found[path][dll]` was throwing a `TypeError`: `found[path]` is a list not a dict, so we must use 
`found[path].remove(dll)` instead.
Tested locally using https://github.com/bottlesdevs/components/pull/236 allowing to use an up-to-date `vkd3d-proton` including the new dll.

Add support for newer vkd3d-proton + bug fix

---

com.usebottles.bottles.yml

This uses the correct URL for xdpyinfo. The GitHub repo was deleted, so I'm using the GitLab repo instead.

fix: Use correct xdpyinfo URL

---

bottles/backend/managers/steam.py

Use bottle name instead of path in launch options when adding a Steam shortcut

---

bottles/backend/managers/manager.py
bottles/frontend/ui/preferences.blp
bottles/frontend/views/preferences.py

On first launch, download stable components instead of unstable/experimental builds.
Additionally, the pre-release/unstable switch now includes components as well.
Basically this PR extends the existing behavior of runners to runners _and_ components.
Fixes #2825
Tested locally on a clean environment.

Download stable component on first launch

---

bottles/frontend/main.py

This fixes the NameError when running `flatpak run com.usebottles.bottles//stable --version`.
Fixes https://github.com/bottlesdevs/Bottles/issues/2891

cli: Fix app version error

---

README.md

The old URL went to a link that had a certificate with a CN of forum.usebottles.com. This this makes the URL that so that people don't get a certificate error.
N/A

Fix forum URL

---

bottles/frontend/windows/display.py

Somehow using get_state and set_state on switches will sometimes make them render incorrectly.
Switching to get_active and set_active seems to fix this issue. 
Fixes #2877
Toggled the switches and saved and reloaded the settings multiple times

get/set_active instead of get/set_state for switch

---

README.md

It's pretty clear that the Bottles developers don't want the package to be packaged at all for distributions. Having rules on your README gives the notion that you *are* actually in favour of people doing so. Removing this section will remove that doubt.

Remove the package maintainer section from README

---

CONTRIBUTING.md
README.md
utils/install.sh
utils/uninstall.sh

Related: https://github.com/bottlesdevs/Bottles/issues/2921
- See branch

misc: Improve README and build instructions to favor Flatpak

---

bottles/backend/wine/winecommand.py

winecommand: Fix LatencyFleX enablement

---

bottles/frontend/windows/gamescope.py
bottles/frontend/windows/vkbasalt.py
bottles/frontend/windows/vmtouch.py

`state` should only be used when the switch is in a working state.

frontend: Use active instead of state property

---

bottles/backend/managers/manager.py
bottles/backend/runner.py
bottles/backend/utils/generic.py
bottles/backend/utils/steam.py
bottles/frontend/views/preferences.py
bottles/frontend/widgets/component.py

Reported fixes:
- Fixes #2956
- Preliminary work for #1244
- Use some feedback given on #2703: explains a bit more about the difference between `Proton GE` and `Wine GE`, which now use their correct name.
Unreported fixes:
- Fixes related to `Proton` being confused as a type where it's a name/prefix and vice versa.
- Fixes and optimizations related to runners/components ordering/sorting.
- Refactoring in `preferences.py` for less duplicate code.
- Other minor fixes
Notably, finally gives Kron4ek builds some love with a proper title and description. Those builds are updated regularly, integrated with the CI, and were responsible for 99% of the builds in `Other` (the 1% being old broken release which will be removed soon in the components repository), giving them a proper description makes …

fix: Offline components and runners not manageable

---

bottles/frontend/views/bottle_details.py
bottles/frontend/windows/launchoptions.py

LaunchOptionsDialog was handling program configuration incorrectly in some cases:
- When editing Launch options immediately after creating new entry. It tried to read properties that didn't exist from program dict
```
Traceback (most recent call last):
File "/home/piotrek/dev/Bottles/bottles/frontend/widgets/program.py", line 134, in show_launch_options_view
dialog = LaunchOptionsDialog(self, self.config, self.program)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/piotrek/dev/Bottles/bottles/frontend/windows/launchoptions.py", line 118, in __init__
self.action_cwd.set_subtitle(program["folder"])
~~~~~~~^^^^^^^^^^
KeyError: 'folder'
```
- When saving configuration, signal handler was converting `dict` to `str`
```Traceback (most recent call last):
File …
```

Fix adding new executables to bottle and updating launch options

---

bottles/backend/wine/drives.py
bottles/frontend/windows/drives.py

Fixes the ability to change the path of a drive in a bottle. Works by removing the symlink before adding a new changed symlink to prevent errors.
Fixes #(issue)
1. Change directory of drive 
2. Error appears "Drive a: already exists in the bottle, no drive added"
1. Change directory of drive 
2. No error appears and directory changes.

Fixed ability to change drive location

---

bottles/backend/managers/runtime.py
bottles/backend/managers/steam.py
bottles/backend/utils/steam.py
bottles/backend/wine/winecommand.py
bottles/backend/wine/wineserver.py
com.usebottles.bottles.yml

Fixes #2952
Fixes #2850
To completely fix those issues, `Proton-GE` runners manifests should be updated in the [components](https://github.com/bottlesdevs/components) repository. It is independent from this PR and will not require further `Bottles` code change.
I described what the issue is and how to fix it in the linked issues, pasting those comments for reference: 
>There is two bugs here.
The first one is on the [component](https://github.com/bottlesdevs/components) side and match what you described: there is a mismatch between the component name (lower-case) and the extracted component directory (which contains capitalized letters). 
Concerning the fix: should we change the extracted folder name to lower-case, or the component name to include those capitalized letters? Capitalizing …

fix: Steam and Proton usage

---

.github/workflows/mypy.yml
.github/workflows/sonar.yml

For a full read: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
For a tl;dr: `Combining pull_request_target workflow trigger with an explicit checkout of an untrusted PR is a dangerous practice that may lead to repository compromise.`
Additionally, fix SonarQube which basically never worked since its introduction.

workflow: Use more secure pull_request trigger and fix SonarQube

---

sonar-project.properties

Fix the following analysis warning:
`Your code is analyzed as compatible with python 2 and 3 by default. This will prevent the detection of issues specific to python 2 or python 3. You can get a more precise analysis by setting a python version in your configuration via the parameter "sonar.python.version"`

configuration: Set python version to 3 in sonar-project.properties

---

bottles/backend/wine/winecommand.py
bottles/frontend/views/bottle_taskmanager.py
bottles/frontend/views/preferences.py

Fix a bug which caused components/runners not to be listed when pre-release is checked off and unstable components/runners were installed.
Fixes #3047
Includes two unrelated one-liner fixes:
Fixed #3051
Fixes #3050
Locally with build artifacts.

fix: Components/Runners not showing when pre-release is off and steam runtime compatibility with wine runners

---

bottles/backend/wine/winecommand.py

Currently the `get_cmd` function always ignores "sniper" if "scout" is presented while setting steam runtime, the second `if` should be `elif`.
[Bottles/bottles/backend/wine/winecommand.py: 506](https://github.com/bottlesdevs/Bottles/blob/c2c323706b620fe696d3f27ffa700a8e4d06fe10/bottles/backend/wine/winecommand.py#L506C12-L506C12)

fixed steam runtime path in WineCommand:get_cmd

---

.github/dependabot.yml
.github/workflows/build_flatpak.yml
.github/workflows/close-issues.yml
.github/workflows/mypy.yml
.github/workflows/pylint-checker.yml
.github/workflows/pylint-commenter.yml
.github/workflows/pytest.yml
.github/workflows/sonar.yml
.github/workflows/update-manifest.yml

Use dependabot to automatically update actions, like in the `components` repository: https://github.com/bottlesdevs/components/pull/291

automation: Use dependabot to update actions

---

bottles/backend/managers/manager.py
bottles/backend/managers/repository.py
bottles/backend/state.py
bottles/backend/utils/connection.py
bottles/frontend/ui/loading.blp
bottles/frontend/ui/preferences.blp
bottles/frontend/views/loading.py
bottles/frontend/views/preferences.py
bottles/frontend/windows/main_window.py
data/com.usebottles.bottles.gschema.xml

Adds a button to skip startup connections and go to offline mode to help with Bottles startup on slow and unstable connections.
Adds "Force Offline Mode" setting in preferences/General/Advanced as option to immediately start Bottles on slow and unstable connections.
Fixes #2954 problem for me
- `sudo wondershaper $NET_INTERFACE 100 100` to limit your connection speed
- run Bottles and test.
Skip button correctly handles skipping 2 stage connection pings and downloading of repositories indexes

Improve bad connections handling

---

bottles/backend/health.py
bottles/frontend/views/bottle_preferences.py
bottles/frontend/windows/dlloverrides.py
bottles/frontend/windows/drives.py
bottles/frontend/windows/envvars.py
bottles/frontend/windows/exclusionpatterns.py
bottles/frontend/windows/fsr.py
bottles/frontend/windows/gamescope.py
bottles/frontend/windows/sandbox.py
bottles/frontend/windows/vmtouch.py

This reverts commit 38cad2d98d4bf528679a05b61322ec7f8954dcae.
See #3109, it has issues beyond the health checks being broken.
Fixes #3108

Revert "Minor improvements (#3102)"

---

bottles/backend/health.py

When checking for Wayland also check for ```WAYLAND_SOCKET```.
Fixes #3134
- [ x] Bug fix (non-breaking change which fixes an issue)
Minimal --> not tested

Add WAYLAND_SOCKET check

---

bottles/backend/managers/dependency.py

The ```__step_cab_extract``` method currently returns ```True``` even if the download fails. This leads to Bottles showing a dependency as installed when it isn't. This fix adds the needed return logic for such cases.
Fixes #3145
- [ x] Bug fix (non-breaking change which fixes an issue)
Minimal change -> not tested.

Fail on unsuccessful cab_extract download

---

bottles/backend/managers/dependency.py
bottles/frontend/views/bottle_dependencies.py
bottles/frontend/widgets/dependency.py

Superseed #3058, thanks to Kinsteen for his work on this!
Fixes https://github.com/bottlesdevs/Bottles/issues/2918
Fixes https://github.com/bottlesdevs/Bottles/issues/2166

Allow dependencies to be installed in 32 bits bottle

---

bottles/backend/globals.py
bottles/frontend/views/bottle_preferences.py

It will not work if the versions don't match.

fix: MangoHud, gamescope and vkBasalt versions

---

bottles/backend/dlls/dll.py
bottles/backend/dlls/dxvk.py
bottles/backend/dlls/latencyflex.py
bottles/backend/dlls/nvapi.py
bottles/backend/dlls/vkd3d.py
bottles/backend/managers/epicgamesstore.py
bottles/backend/managers/manager.py
bottles/backend/managers/steam.py
bottles/backend/managers/ubisoftconnect.py
bottles/backend/utils/steam.py
bottles/backend/utils/terminal.py
bottles/backend/wine/executor.py
bottles/backend/wine/winecommand.py
bottles/frontend/cli/cli.py
bottles/frontend/ui/dialog-dll-overrides.blp
bottles/frontend/windows/dlloverrides.py
bottles/frontend/windows/envvars.py
bottles/frontend/windows/launchoptions.py

Various bug fixes and cleanups.
Non exhaustive list:
- Fixes #3081
- Fixes #947
- Fixes #2903
- Fixes #3149
- Fixes programs/global overrides logic (backend).
- Fixes programs/global overrides logic (frontend).
- Fixes programs `WINEDLLOVERRIDES` not applying.
- Fixes programs `%command%` parsing.
- Fixes programs not launching from terminal if `arguments` contain environment variables.
- Add a check to verify the `Environment Variables` feature does not overlap with the `DLL Overrides` feature.
- Add a check to verify the `DLL Overrides` feature does not overlap with overrides managed by Bottles (e.g. DXVK, VKD3D...)
- Some cleanups and refactoring where I could.
And probably more that I've forgotten...
\
It already required **a lot** of work and, unless it's an absolute necessity, I'm …

fix: Various bug fixes and cleanups

---

bottles/frontend/views/bottle_details.py

Fix for #3199 that adds a "all files" option to the "add shortcuts" file picker as a workaround for a gnome bug
Fixes #3199

Add "all files" to the "add shortcuts" file picker

---

bottles/backend/models/samples.py
bottles/frontend/cli/cli.py
bottles/frontend/windows/launchoptions.py

fix: run program from CLI and launch preferences

---

bottles/backend/wine/winecommand.py

Partially split off from #2840, since that is stalled (it will need to be rebased later).
Fixes #3065, fixes #3195.
Not really tested, tbh.

fix: Gamescope options arguments

---

.github/workflows/update-manifest.yml
com.usebottles.bottles.pypi-deps.yaml
com.usebottles.bottles.yml
requirements.dev.txt
requirements.txt

Update GNOME runtime to 46.
Also update every other dependencies (automated).
Fix `update-manifest.yml`

manifest: Update GNOME runtime to 46 and fix automation

---

bottles/backend/managers/repository.py

So if for any reason [components, dependencies or programs are not being updated](https://github.com/bottlesdevs/Bottles/issues/3458)... users will be able to fork and update themselves easily(like `PERSONAL_COMPONENTS=https://github.com/Vingian/Bottles_components/raw/main`). The possibility of using a local repository is maintained by simply specifying `file://`(like `PERSONAL_COMPONENTS=file:///home/Vingian/Bottles_components`).

feat: support for personal repos

---

bottles/backend/wine/winecommand.py

The generated Gamescope wrapper script should pass all its arguments to the target application. This PR enables the correct behavior expected by users who have Gamescope enabled.
Fixes #3194
For the following tests, the target application should react in some way to command arguments.

Bug Fix: added $@ parameter in the Gamescope wrapper script

---

bottles/backend/managers/manager.py
bottles/backend/models/samples.py
bottles/backend/wine/executor.py
bottles/backend/wine/winecommand.py
bottles/frontend/cli/cli.py
bottles/frontend/ui/dialog-launch-options.blp
bottles/frontend/windows/launchoptions.py

Allows Gamescope to be toggled on a program-by-program basis, instead of just bottle-wide. This means that you can either leave the global toggle off and enable it for individual programs (default settings will be used) or leave it global-on and disable on specific ones.
All in all, avoids the hassle of having to manage two near-identical instances of the same bottle just to deal with gamescope-ness.
Closes #3377 (well-requested feature).
Try toying with different values for Gamescope (global setting and individual override):
- Override not set (`gamescope: null` in `bottle.yml`) should just be ignored
- Override toggled on (`gamescope: true`) should _always_ start said game with Gamescope
- Override toggled off (`gamescope: false`) should _never_ start said game with Gamescope

Add Gamescope toggle as an override for individual programs

---

build-aux/com.usebottles.bottles.Devel.json

- remove node anchor used in the yml version
- remove gamemode module (freedesktop sdk 24.08 has already bundled)
- disable portal-tests, vala binds and gtk3 backend of libportal
- make explicit the buildsystem of imagemagick

build(flatpak): more improvements to manifest

---

bottles/frontend/cli/cli.py

Fix starting an --executable from the CLI.
Seems like this is broken since commit f31c0a7, which was an improvement for the `--program` case but neglected the `--executable` case.
Fixes #3599 #3601
Right-click on a program.exe on Nautilus and open it with Bottles.  
Command lines:
```
flatpak run --command=bottles-cli com.usebottles.bottles.Devel run --bottle test-cli --program linksider
flatpak run --command=bottles-cli com.usebottles.bottles.Devel run --bottle test-cli --executable /path/to/linksider.exe
flatpak run com.usebottles.bottles.Devel /path/to/linksider.exe
```

fix[close #3599]: CLI no longer works when starting a Bottle

---

bottles/frontend/main.py
bottles/frontend/ui/bottles.gresource.xml
bottles/frontend/ui/help-overlay.blp
bottles/frontend/ui/meson.build
bottles/frontend/ui/window.blp

This includes parts of https://github.com/bottlesdevs/Bottles/pull/2683

Add keyboard shortcuts dialog

---

bottles/frontend/windows/launchoptions.py

- Use `FileDialog` throughout
- Handle whatever `GLib.Error` throws our way
- Handle it the same way regardless of dialog

Use FileDialog for all file/path pickers

---

bottles/frontend/views/bottle_preferences.py
bottles/frontend/windows/fsr.py
bottles/frontend/windows/mangohud.py
bottles/frontend/windows/vkbasalt.py

This reverts https://github.com/bottlesdevs/Bottles/pull/3600, except https://github.com/bottlesdevs/Bottles/pull/3600/commits/c4a45a548546fbb213959e4f74ecec00ce945c0f.
The bug in https://github.com/bottlesdevs/Bottles/issues/3594 was caused by https://github.com/bottlesdevs/Bottles/pull/3591/commits/cb5dab26cec790f856555245caddd1b152bd7011.

Make bottle preferences code hotter take 2

---

.github/workflows/build_flatpak.yml
build-aux/com.usebottles.bottles.Devel.json

As discussed internally, it was a rushed and nondemocratic decision
to apply this commit without asking anybody else.

Revert "flatpak: Use `master` runtime version"

---

bottles/frontend/widgets/component.py

The download progress is reported from a thread and Gtk is not thread-safe. This fixes issues with the UI breaking when downloading runners/components.
Fixes #3578
Fixes #3553
Fixes #3629
The issue can be more easily reproduced by downloading a big runner like proton-ge. The UI would often freeze, and sometimes all widgets would disappear. Program crashes also reported by users, but I could never reproduce a crash.

component: Schedule progress to run on main loop

---

bottles/frontend/views/bottle_details.py

Set the initial directory for the Add Shortcuts dialog to the root of the bottle.
Fixes #3475.

Start "Add Shortcuts" dialog at the root of the bottle

---

bottles/backend/utils/vulkan.py

Removes the workaround implemented specifically for the NVIDIA Flatpak drivers (5627b5b).
Originally, the issue was brought up in flathub/org.freedesktop.Platform.GL.nvidia#112. flathub/org.freedesktop.Platform.GL.nvidia#331 solves the problem on the driver side.
In the debug information, under `Graphics -> vendors -> nvidia -> icd`, there will be a list of Vulkan `.json` files.

Remove NVIDIA Flatpak Workaround

---

data/com.usebottles.bottles.metainfo.xml.in.in

It appears that the appstream project no longer supports `translatable=no` properties, and gettext extract the `translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no` properties are not accepted by developers. You can find the issue here: https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
Please include a summary of the …

appdata: `translate=no` properties

---

bottles/frontend/program_row.py

bottles/frontend/program_row.py
In the past it dosent give any feedback to the user if it failed adding to the steam library.
(It dosent work if you have Flatpak version of steam)
I read most of the issues and there is no issues for this problem.
Since this isn't a big change I have only built it and tested it on my main distro (OpenSUSE Tumbelweed)

frontend: Added 'Failed adding to Steam Library dialog' in program_row.py' dialog

---

bottles/backend/wine/winecommand.py

Please include a summary of the change and which issue is fixed (if available).
Fixes #3781 
Please describe the tests that you ran to verify your changes.
I tested it on
- kron4ek-wine-10.2
- kron4ek-wine-9.21
- ge-proton-9-25

fix: use correct wine path on 10.2 and above

---

bottles/frontend/check-row.blp

The GtkListBox::row-activated signal only emits when a row is activated, not the child widget. This means, the check button wouldn't trigger the emission of the signal, thereby not updating the NewBottleDialog:selected-environment property.
Fixes https://github.com/bottlesdevs/Bottles/issues/3740

bottle-row: Set can-target and can-focus to false

---

README.md

This pull request updates the sponsors section in the README.
It fixes the broken JetBrains logo link by replacing it with the official one and changes the layout to a centered, vertical format with consistent logo sizes for improved visual clarity and alignment.
- Verified that the JetBrains logo now displays correctly in the sponsors section.
- Checked the README preview on GitHub to confirm that all sponsor logos are centered, evenly sized, and visually consistent on both a Full HD screen and a mobile phone.

Jetbrains logo
